version: "3"
services:
  app:
    build: app
    ports:
      - "0.0.0.0:80:80"
    restart: always
    pid: "host"
    cap_add:
      - CHECKPOINT_RESTORE
      - SYS_PTRACE
    volumes:
      - shared-volume:/app/uploads
    depends_on:
      - checker

  checker:
    build: checker
    pid: "host"
    privileged: true
    restart: always
    expose:
      - 8080
    volumes:
      - shared-volume:/uploads

volumes:
  shared-volume:
