apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  securityContext:
    runAsUser: 10
    runAsNonRoot: false
  containers:
  - name: app
    image: web-app
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 0
